# Generated by Django 3.0.8 on 2020-10-31 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'All User'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'User: Doctor'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'User: Patient'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_patient', to='accounts.Patient'),
        ),
    ]
