# Generated by Django 3.0.8 on 2020-10-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201031_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approved_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
