# Generated by Django 3.0.8 on 2020-10-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appointment_approved_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='approved_for',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
