# Generated by Django 3.0.8 on 2020-11-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201107_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicines',
        ),
    ]
